---
- hosts: master
  tasks:
    - name: create the user
      postgresql_user:
        name: <[ dbuser ]>
        role_attr_flags: SUPERUSER,CREATEROLE,CREATEDB
    - name: create the db
      postgresql_db:
        name: <[ dbname ]>
        owner: <[ dbuser ]>