---
- hosts: gateway
  tasks:
    - name: run terraform
      command: "{{ ansible_env.HOME }}/.dbadmin/bin/terraform apply --state={{ ansible_env.HOME }}/.dbadmin/terraform.tfstate {{ ansible_env.HOME }}/.dbadmin/terraform"
    - name: run gcloud compute config-ssh to set up ssh keys
      expect:
        command: gcloud compute config-ssh
        responses:
          'Enter passphrase \(empty for no passphrase\): ': "\n"
          'Enter same passphrase again: ': "\n"
        creates: ~/.ssh/google_compute_engine
    - name: pause to let ssh credentials propagate
      pause:
        seconds: 30
    - name: do some basic gcloud configuration
      command: gcloud config set compute/zone <[ zone ]>