---
- hosts: master
  tasks:
    - name: copy postgresql configuration file into the data folder
      template: 
        src: config/master/postgresql.j2
        dest: /etc/postgresql/9.6/main/postgresql.conf

    - name: copy pg_hba file into the data folder
      template: 
        src: config/master/pg_hba.j2
        dest: /etc/postgresql/9.6/main/pg_hba.conf

    - name: create repmgr.conf
      template:
        src: config/master/repmgr.j2
        dest: /etc/repmgr.conf

    - block: 
      - name: generate ssh keys
        expect: 
          command: ssh-keygen -t rsa
          responses:
            'Enter file in which to save the key \(/var/lib/postgresql/.ssh/id_rsa\):': "\n"
            'Enter passphrase \(empty for no passphrase\):': "\n"
            'Enter same passphrase again:': "\n"
            
      - name: create config for ssh
        file: 
          path: /var/lib/postgresql/.ssh/config
          state: touch

      - name: add barman server's ip address to config
        lineinfile:
          dest: /var/lib/postgresql/.ssh/config
          line: "Host {{ hostvars[groups['barman'][0]]['hostname'] }}"

      - name: add user to config
        lineinfile:
          dest: /var/lib/postgresql/.ssh/config
          line: 'User barman'

      - name: ignore ssh host key checking
        lineinfile:
          dest: /var/lib/postgresql/.ssh/config
          line: 'StrictHostKeyChecking no'

      - name: create user repmgr
        command: createuser -s repmgr

      - name: create databse repmgr
        command: createdb repmgr -O repmgr
      become: true
      become_method: sudo
      become_user: postgres

    - name: fetch the public key to store in the local box
      fetch:
        src: /var/lib/postgresql/.ssh/id_rsa.pub
        dest: tmp

    - name: restart server
      service:
        name: postgresql
        state: restarted

    - name: reload configuration files
      service:
        name: postgresql
        state: reloaded

    - name: register as master
      command: repmgr -f /etc/repmgr.conf master register
      become: true
      become_user: postgres
      become_method: sudo

- hosts: standby1
  tasks:
    - name: copy postgresql configuration file into the data folder
      template: 
        src: config/standby/standby_one/postgresql.j2
        dest: /etc/postgresql/9.6/main/postgresql.conf

    - name: copy pg_hba file into the data folder
      template: 
        src: config/standby/standby_one/pg_hba.j2
        dest: /etc/postgresql/9.6/main/pg_hba.conf

    - name: create repmgr.conf
      template:
        src: config/standby/standby_one/repmgr.j2
        dest: /etc/repmgr.conf


- hosts: standby2
  tasks:
    - name: copy postgresql configuration file into the data folder
      template: 
        src: config/standby/standby_two/postgresql.j2
        dest: /etc/postgresql/9.6/main/postgresql.conf

    - name: copy pg_hba file into the data folder
      template: 
        src: config/standby/standby_two/pg_hba.j2
        dest: /etc/postgresql/9.6/main/pg_hba.conf

    - name: create repmgr.conf
      template:
        src: config/standby/standby_two/repmgr.j2
        dest: /etc/repmgr.conf


- hosts: standby
  tasks: 
    - name: add postgres as a sudoer
      lineinfile:
        dest: /etc/sudoers.d/postgres
        line: >
          postgres ALL=(root) NOPASSWD: /bin/systemctl start postgresql, 
          /bin/systemctl stop postgresql, 
          /bin/systemctl restart postgresql, 
          /bin/systemctl reload postgresql, 
          /usr/bin/pg_ctlcluster 9.6 main promote
        create: yes
        state: present
        mode: 0600

    - name: install barman-cli
      apt: 
        name: barman-cli

    - block: 
      - name: generate ssh keys
        expect: 
          command: ssh-keygen -t rsa
          responses:
            'Enter file in which to save the key \(/var/lib/postgresql/.ssh/id_rsa\):': "\n"
            'Enter passphrase \(empty for no passphrase\):': "\n"
            'Enter same passphrase again:': "\n"
            
      - name: create config for ssh
        file: 
          path: /var/lib/postgresql/.ssh/config
          state: touch

      - name: add barman server ip address to config
        lineinfile:
          dest: /var/lib/postgresql/.ssh/config
          line: "Host {{ hostvars[groups['barman'][0]]['hostname'] }}"
      
      - name: add user to config
        lineinfile:
          dest: /var/lib/postgresql/.ssh/config
          line: 'User barman'

      - name: ignore ssh host key checking
        lineinfile:
          dest: /var/lib/postgresql/.ssh/config
          line: 'StrictHostKeyChecking no'

      - name: copy barman public key into authorized_keys
        copy:
          src: tmp/machine1/var/lib/barman/.ssh/id_rsa.pub
          dest: /var/lib/postgresql/.ssh/authorized_keys
          mode: 0600
      become: true
      become_method: sudo
      become_user: postgres

    - name: fetch the public key to store in the local box
      fetch:
        src: /var/lib/postgresql/.ssh/id_rsa.pub
        dest: tmp


