---
- hosts: haproxy
  tasks:
    - name: enable the backports repository
      apt_repository:
        repo: deb http://httpredir.debian.org/debian jessie-backports main
        state: present
        filename: '/etc/apt/sources.list.d/backports.list'

    - name: update the package lists
      apt: 
        update_cache: yes

    - name: install haproxy
      apt:
        name: haproxy
        default_release: jessie-backports

    - name: get haproxy configuration
      copy:
        src: config/haproxy.cfg
        dest: /etc/haproxy/haproxy.cfg

    - name: restart haproxy
      service:
        name: haproxy
        state: restarted

    - name: add source repository into source list
      apt_repository:
        repo: deb http://apt.postgresql.org/pub/repos/apt/ jessie-pgdg main
        state: present
        filename: '/etc/apt/sources.list.d/pgdg.list'

    - name: import the repository signing key
      apt_key:
        url: "https://www.postgresql.org/media/keys/ACCC4CF8.asc"
        state: present

    - name: update the package lists
      apt: 
        update_cache: yes

    - name: install postgresql-9.6
      apt:
        name: postgresql-9.6
    
    - name: create directory .ssh
      file:
        path: ~/.ssh
        state: directory
        mode: 0700

    - name: copy postgresql public key into authorized_keys
      copy:
        src: tmp/machine2/var/lib/postgresql/.ssh/id_rsa.pub
        dest: ~/.ssh/authorized_keys
        mode: 0600

    - name: add standby1's public key into authorized_keys
      lineinfile:
        dest: ~/.ssh/authorized_keys
        line: "{{ lookup('file', 'tmp/machine3/var/lib/postgresql/.ssh/id_rsa.pub') }}"

    - name: add standby2's public key into authorized_keys
      lineinfile:
        dest: ~/.ssh/authorized_keys
        line: "{{ lookup('file', 'tmp/machine4/var/lib/postgresql/.ssh/id_rsa.pub') }}"