---
- hosts: all
  tasks:
    - name: install dbus
      apt:
        update_cache: yes
        name: dbus

    - name: install rsync
      apt:
        name: rsync
    - name: change the hostname
      hostname:
        name: "{{ hostname }}"

    - name: add new hostname in /etc/hosts
      lineinfile:
        dest: /etc/hosts
        line: '127.0.0.1 {{ hostname }} {{ hostname }}' 

    - template: 
        src: ../ip.j2
        dest: /var/lib/ip_tmp

    - name: get the content inside the ip_tmp file
      shell: "cat /var/lib/ip_tmp"
      register: ip

    - name: put the ip addresses of all machines into hosts file
      lineinfile:
        dest: /etc/hosts
        line: "{{ ip.stdout }}"




