---
- hosts: standby
  tasks:   
    - name: stop standby server
      service:
        name: postgresql
        state: stopped

    - name: remove postgresql data folder to prepare for standby clone
      file:
        path: /var/lib/postgresql/9.6/main/
        state: absent

    - name: clone standby
      command: >
        repmgr -h {{ hostvars[groups['master'][0]]['hostname'] }} -d repmgr
        -D /var/lib/postgresql/9.6/main -f /etc/repmgr.conf standby clone
      become: true
      become_user: postgres
      become_method: sudo

    - name: start server
      service:
        name: postgresql
        state: started

    - name: reload configuration files
      service:
        name: postgresql
        state: reloaded
    
    - name: find if host is already registered with repmgr
      command: psql -U repmgr -d repmgr -c "copy(select type from repmgr_master.repl_nodes where conninfo like '%{{ ansible_hostname }}%') to stdout with csv;"
      register: host_replica_type
      ignore_errors: true
      tags: debug

    - block:
      - name: register as standby
        command: repmgr -f /etc/repmgr.conf standby register
        when:  '"standby" not in host_replica_type.stdout'

      - name: start repmgrd
        shell: >
          repmgrd -f /etc/repmgr.conf -d --verbose >> 
          /var/log/postgresql/postgresql-9.6-main.log 2>&1
      become: true
      become_user: postgres
      become_method: sudo
